# EDA
## Univariate EDA

In [20]:
import sys
import os
# Add src/ to path so sibling packages are importable
sys.path.insert(0, os.path.abspath(os.path.join(os.getcwd(), '..')))

from diagnostics import diagnose_data

In [21]:
# Libraries
import os
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from kaggle_interaction.load import load_data
from training_split import train_val_split

In [22]:
cwd = os.getcwd()
print(f'current working directory: {cwd}')
pd.set_option("display.max_columns", None)

current working directory: /Users/lukazaitch/MSc AI/Programming/Y1P5/dmt-2/src/notebooks

In [23]:
train_set, test_set = load_data()
train_set, val_set = train_val_split(train_set, train_ratio=0.8)

In [24]:
n_rows = 2000
display(train_set.head(n_rows))
display(val_set.head(n_rows))
display(test_set.head(n_rows))
print('train_set shape:', train_set.shape)
print('val_set shape:', val_set.shape)
print('test_set shape:', test_set.shape)

,srch_id,date_time,site_id,visitor_location_country_id,visitor_hist_starrating,visitor_hist_adr_usd,prop_country_id,prop_id,prop_starrating,prop_review_score,prop_brand_bool,prop_location_score1,prop_location_score2,prop_log_historical_price,position,price_usd,promotion_flag,srch_destination_id,srch_length_of_stay,srch_booking_window,srch_adults_count,srch_children_count,srch_room_count,srch_saturday_night_bool,srch_query_affinity_score,orig_destination_distance,random_bool,comp1_rate,comp1_inv,comp1_rate_percent_diff,comp2_rate,comp2_inv,comp2_rate_percent_diff,comp3_rate,comp3_inv,comp3_rate_percent_diff,comp4_rate,comp4_inv,comp4_rate_percent_diff,comp5_rate,comp5_inv,comp5_rate_percent_diff,comp6_rate,comp6_inv,comp6_rate_percent_diff,comp7_rate,comp7_inv,comp7_rate_percent_diff,comp8_rate,comp8_inv,comp8_rate_percent_diff,click_bool,gross_bookings_usd,booking_bool
1219448,81578,2012-11-01 00:08:29,5,219,NaN,NaN,219,93974,4,4.5,1,5.17,0.6352,5.72,12,195.0,1,17012,1,15,2,0,1,1,NaN,355.82,1,NaN,NaN,NaN,0.0,0.0,NaN,0.0,0.0,NaN,NaN,NaN,NaN,1.0,0.0,8.0,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,NaN,0,NaN,0
1219451,81578,2012-11-01 00:08:29,5,219,NaN,NaN,219,133689,4,4.5,1,5.19,0.6166,5.75,2,179.0,0,17012,1,15,2,0,1,1,NaN,355.78,1,NaN,NaN,NaN,0.0,0.0,NaN,0.0,0.0,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,NaN,0,NaN,0
1219450,81578,2012-11-01 00:08:29,5,219,NaN,NaN,219,119527,4,4.5,1,5.18,0.6132,5.82,36,189.0,0,17012,1,15,2,0,1,1,NaN,355.79,1,NaN,NaN,NaN,0.0,0.0,NaN,0.0,0.0,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,NaN,0,NaN,0
1219449,81578,2012-11-01 00:08:29,5,219,NaN,NaN,219,95095,5,4.5,1,4.93,0.1350,6.21,27,395.0,0,17012,1,15,2,0,1,1,NaN,355.70,1,NaN,NaN,NaN,0.0,0.0,NaN,0.0,0.0,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,NaN,0,NaN,0
1219419,81578,2012-11-01 00:08:29,5,219,NaN,NaN,219,4080,4,4.5,1,5.18,0.3795,5.84,30,250.0,0,17012,1,15,2,0,1,1,NaN,356.05,1,NaN,NaN,NaN,NaN,NaN,NaN,1.0,0.0,170.0,NaN,NaN,NaN,0.0,0.0,100.0,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,100.0,0,NaN,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3563305,239305,2012-11-01 07:12:34,5,219,NaN,NaN,205,10895,4,4.0,1,1.61,0.0116,5.36,25,142.0,0,28317,4,36,2,0,1,1,NaN,8434.97,1,NaN,NaN,NaN,0.0,0.0,NaN,0.0,0.0,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,0
3563306,239305,2012-11-01 07:12:34,5,219,NaN,NaN,205,13283,5,4.5,1,0.69,0.0010,5.34,31,139.0,0,28317,4,36,2,0,1,1,NaN,8432.50,1,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,0
3563307,239305,2012-11-01 07:12:34,5,219,NaN,NaN,205,40027,4,4.5,1,4.61,0.0831,5.44,1,178.0,0,28317,4,36,2,0,1,1,NaN,8435.03,1,NaN,NaN,NaN,0.0,0.0,NaN,0.0,0.0,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,0
3563308,239305,2012-11-01 07:12:34,5,219,NaN,NaN,205,50009,4,4.0,0,0.69,0.0059,4.85,32,127.0,1,28317,4,36,2,0,1,1,NaN,8433.80,1,NaN,NaN,NaN,0.0,0.0,NaN,0.0,0.0,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,0
3563326,239305,2012-11-01 07:12:34,5,219,NaN,NaN,205,105270,4,4.5,1,0.00,0.0075,5.12,20,123.0,1,28317,4,36,2,0,1,1,NaN,8436.01,1,NaN,NaN,NaN,0.0,0.0,NaN,0.0,0.0,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,NaN,0

,srch_id,date_time,site_id,visitor_location_country_id,visitor_hist_starrating,visitor_hist_adr_usd,prop_country_id,prop_id,prop_starrating,prop_review_score,prop_brand_bool,prop_location_score1,prop_location_score2,prop_log_historical_price,position,price_usd,promotion_flag,srch_destination_id,srch_length_of_stay,srch_booking_window,srch_adults_count,srch_children_count,srch_room_count,srch_saturday_night_bool,srch_query_affinity_score,orig_destination_distance,random_bool,comp1_rate,comp1_inv,comp1_rate_percent_diff,comp2_rate,comp2_inv,comp2_rate_percent_diff,comp3_rate,comp3_inv,comp3_rate_percent_diff,comp4_rate,comp4_inv,comp4_rate_percent_diff,comp5_rate,comp5_inv,comp5_rate_percent_diff,comp6_rate,comp6_inv,comp6_rate_percent_diff,comp7_rate,comp7_inv,comp7_rate_percent_diff,comp8_rate,comp8_inv,comp8_rate_percent_diff,click_bool,gross_bookings_usd,booking_bool
1416055,94943,2013-05-21 16:56:39,32,220,NaN,NaN,15,125574,5,4.0,0,3.81,NaN,5.48,31,283.31,0,16160,2,42,1,5,1,0,NaN,NaN,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,0
1416056,94943,2013-05-21 16:56:39,32,220,NaN,NaN,15,125860,5,0.0,1,2.83,NaN,5.90,7,713.66,0,16160,2,42,1,5,1,0,NaN,NaN,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-1.0,0.0,9.0,0.0,0.0,9.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,0
1416058,94943,2013-05-21 16:56:39,32,220,NaN,NaN,15,129796,5,4.0,1,4.64,0.0147,5.74,13,669.54,0,16160,2,42,1,5,1,0,NaN,NaN,1,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN,0.0,0.0,NaN,0.0,0.0,NaN,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,0
1416059,94943,2013-05-21 16:56:39,32,220,NaN,NaN,15,129847,5,4.5,1,2.89,0.1087,6.08,3,682.29,0,16160,2,42,1,5,1,0,NaN,NaN,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,NaN,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,0
1416060,94943,2013-05-21 16:56:39,32,220,NaN,NaN,15,129908,4,4.5,1,4.42,0.0479,5.25,10,197.04,0,16160,2,42,1,5,1,0,NaN,NaN,1,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN,0.0,0.0,NaN,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,NaN,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2682280,179990,2013-05-21 18:14:15,5,219,NaN,NaN,219,99353,3,4.5,0,4.44,0.1430,5.50,14,260.00,0,27730,1,16,2,0,1,1,NaN,NaN,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,0
2682263,179990,2013-05-21 18:14:15,5,219,NaN,NaN,219,21693,3,4.0,1,2.64,0.0693,5.40,36,189.00,0,27730,1,16,2,0,1,1,NaN,NaN,1,NaN,NaN,NaN,0.0,0.0,5.0,-1.0,0.0,5.0,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,5.0,0,NaN,0
2682262,179990,2013-05-21 18:14:15,5,219,NaN,NaN,219,19956,4,4.0,1,4.36,0.1194,6.21,28,545.00,0,27730,1,16,2,0,1,1,NaN,NaN,1,NaN,NaN,NaN,0.0,0.0,NaN,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,NaN,0,NaN,0
2682268,179990,2013-05-21 18:14:15,5,219,NaN,NaN,219,36952,4,4.5,1,4.36,0.1195,6.12,31,259.00,0,27730,1,16,2,0,1,1,NaN,NaN,1,NaN,NaN,NaN,0.0,0.0,NaN,0.0,0.0,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,NaN,0,NaN,0
2682265,179990,2013-05-21 18:14:15,5,219,NaN,NaN,219,33023,4,4.5,0,4.19,0.1156,6.08,9,289.00,0,27730,1,16,2,0,1,1,NaN,NaN,1,NaN,NaN,NaN,0.0,0.0,NaN,0.0,0.0,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,NaN,0,NaN,0

,srch_id,date_time,site_id,visitor_location_country_id,visitor_hist_starrating,visitor_hist_adr_usd,prop_country_id,prop_id,prop_starrating,prop_review_score,prop_brand_bool,prop_location_score1,prop_location_score2,prop_log_historical_price,price_usd,promotion_flag,srch_destination_id,srch_length_of_stay,srch_booking_window,srch_adults_count,srch_children_count,srch_room_count,srch_saturday_night_bool,srch_query_affinity_score,orig_destination_distance,random_bool,comp1_rate,comp1_inv,comp1_rate_percent_diff,comp2_rate,comp2_inv,comp2_rate_percent_diff,comp3_rate,comp3_inv,comp3_rate_percent_diff,comp4_rate,comp4_inv,comp4_rate_percent_diff,comp5_rate,comp5_inv,comp5_rate_percent_diff,comp6_rate,comp6_inv,comp6_rate_percent_diff,comp7_rate,comp7_inv,comp7_rate_percent_diff,comp8_rate,comp8_inv,comp8_rate_percent_diff
0,1,2013-02-02 15:27:40,24,216,NaN,NaN,219,3180,3,4.5,1,2.94,0.0691,5.03,119.0,0,19222,1,10,2,0,1,0,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1,2013-02-02 15:27:40,24,216,NaN,NaN,219,5543,3,4.5,1,2.64,0.0843,4.93,118.0,0,19222,1,10,2,0,1,0,NaN,NaN,0,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,1,2013-02-02 15:27:40,24,216,NaN,NaN,219,14142,2,3.5,1,2.71,0.0556,4.16,49.0,0,19222,1,10,2,0,1,0,NaN,NaN,0,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,0.0,10.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,1,2013-02-02 15:27:40,24,216,NaN,NaN,219,22393,3,4.5,1,2.40,0.0561,5.03,143.0,0,19222,1,10,2,0,1,0,NaN,NaN,0,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,1,2013-02-02 15:27:40,24,216,NaN,NaN,219,24194,3,4.5,1,2.94,0.2090,4.72,79.0,0,19222,1,10,2,0,1,0,NaN,NaN,0,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1995,128,2012-12-14 17:28:09,5,219,NaN,NaN,219,1209,2,5.0,1,0.00,0.0000,4.59,69.0,0,1986,1,1,1,0,1,1,NaN,67.55,1,NaN,NaN,NaN,0.0,0.0,22.0,-1.0,0.0,22.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,28.0
1996,128,2012-12-14 17:28:09,5,219,NaN,NaN,219,2543,3,3.0,1,3.22,0.0655,4.83,59.0,0,1986,1,1,1,0,1,1,NaN,57.22,1,NaN,NaN,NaN,0.0,0.0,NaN,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,NaN
1997,128,2012-12-14 17:28:09,5,219,NaN,NaN,219,8682,3,4.5,1,2.71,0.0188,4.85,100.0,0,1986,1,1,1,0,1,1,NaN,62.04,1,NaN,NaN,NaN,0.0,0.0,NaN,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,NaN
1998,128,2012-12-14 17:28:09,5,219,NaN,NaN,219,9855,3,4.5,1,2.77,0.0069,4.95,94.0,0,1986,1,1,1,0,1,1,NaN,62.91,1,NaN,NaN,NaN,0.0,0.0,NaN,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,NaN
1999,128,2012-12-14 17:28:09,5,219,NaN,NaN,219,14198,2,3.5,1,2.40,0.0092,4.77,79.0,0,1986,1,1,1,0,1,1,NaN,52.04,1,NaN,NaN,NaN,0.0,0.0,NaN,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,NaN

train_set shape: (3980061, 54)
val_set shape: (978286, 54)
test_set shape: (4959183, 50)

In [25]:
display(train_set.columns)
train_excl_attr = set(train_set.columns) - set(test_set.columns)
display("training exclusive attributes: ", train_excl_attr)

Index(['srch_id', 'date_time', 'site_id', 'visitor_location_country_id',
       'visitor_hist_starrating', 'visitor_hist_adr_usd', 'prop_country_id',
       'prop_id', 'prop_starrating', 'prop_review_score', 'prop_brand_bool',
       'prop_location_score1', 'prop_location_score2',
       'prop_log_historical_price', 'position', 'price_usd', 'promotion_flag',
       'srch_destination_id', 'srch_length_of_stay', 'srch_booking_window',
       'srch_adults_count', 'srch_children_count', 'srch_room_count',
       'srch_saturday_night_bool', 'srch_query_affinity_score',
       'orig_destination_distance', 'random_bool', 'comp1_rate', 'comp1_inv',
       'comp1_rate_percent_diff', 'comp2_rate', 'comp2_inv',
       'comp2_rate_percent_diff', 'comp3_rate', 'comp3_inv',
       'comp3_rate_percent_diff', 'comp4_rate', 'comp4_inv',
       'comp4_rate_percent_diff', 'comp5_rate', 'comp5_inv',
       'comp5_rate_percent_diff', 'comp6_rate', 'comp6_inv',
       'comp6_rate_percent_diff', 'comp7_rate', 'comp7_inv',
       'comp7_rate_percent_diff', 'comp8_rate', 'comp8_inv',
       'comp8_rate_percent_diff', 'click_bool', 'gross_bookings_usd',
       'booking_bool'],
      dtype='str')

'training exclusive attributes: '

{'booking_bool', 'click_bool', 'gross_bookings_usd', 'position'}


- Both the training and test sets have close to 5 million instances.
- Training set has 54 attributes, test set has 50
- The training exclusive attributes are:
    - Booking_bool, click_bool, gross_bookings_usd, position
    - These will be excluded, as they do not exist in the test set

In [26]:
train_set = train_set.drop(columns = train_excl_attr)

## Expected Ranges

In [27]:
ranges = {
    "prop_starrating"                   : [0, 5],
    "prop_review_score"                 : [0, 5],
    "prop_brand_bool"                   : [0, 1],
    "srch_saturday_night_bool"          : [0, 1],
    "random_bool"                       : [0, 1],
    "comp_rate"                         : [-1, 1],
    "comp_inv"                          : [0, 1]
}
attributes_to_check = ranges.keys
print("attributes_to_check", attributes_to_check)

attributes_to_check <built-in method keys of dict object at 0x11d388f80>

## Sparsity

In [28]:
sparsity = sum((train_set == 0).astype(int).sum())/train_set.size
print('sparsity of train_set:', sparsity)
diagnose_data(train_set, name = 'train_set')

sparsity of train_set: 0.12731345574854255
+++ Data Diagnostics +++
Diagnostics for train_set:
pandas DataFrame
Shape: (3980061, 50)
Number of Missing Values: 92223981
Percentage of Missing Values: 46.34%
++++++++++++++++++++++++

- The training set is not particularly sparse
- However, close to half of the data has missing values, which is a problem.
- It's likely that this is systematic missingness: Looking at the first 5 entries of both sets, missingness seems to be pervasive within specific variables:
    - "visitor_hist_starrating", "visitor_hist_adr_usd" : Nulls mean that there is no user history for purchases -> Many customers are new customers. Imputation here could be a neutral value, for example neutral rating and mean average purchase history.
    - "srch_query_affinity_score" : Null means that hotel did not register in searches -> Many hotels did not register in search queries.
    - "orig_destination_distance" : Null means that distance could not be calculated. -> This is potentially a useful attribute, some imputation heuristic could be useful here. For example, we could use "visitor_location_country_id" and compute the distance to the property. 
    - "comp* attributes" : Null means there is no competetive data -> There is no competetive data of certain competitors for certain hotels listed. Question here is what it means that there is no data? Either data is missing at random (measurement error) or competitor x does not have the property in their catalogue, hence no competetive data. The definition of "availability" in the attribute description is not clear: Does no availability mean they have the property, but there are no rooms available, or they do not have the property?
    - Both "prop_review_score" and "prop_review_score"

If visitor has no history, we could also make a new feature; 'hisitor_hist_available'.

## Expedia 
The following sections tries to investigate and familiarize with the expedia webpage and the associated variables.

*Search-specific attributes*:
These are attributes associated with a specific search of a user at a given time. One search usually includes many hotels, each with individual attributes. 
- srch_id, date_time, site_id, visitor_location_country_id: Search metadata 

*User-specific attributes*
- visitor_hist_starrating, visitor_hist_adr_usd: Historical data of the user, such as average rating and prices of hotels stayed at

*Hotel-specific attributes*
- prop_*