# EDA
## Univariate EDA

In [11]:
import sys
import os
from diagnostics import diagnose_data
# Add src/ to path so sibling packages are importable
sys.path.insert(0, os.path.abspath(os.path.join(os.getcwd(), '..')))

In [3]:
# Libraries
import os
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from kaggle_interaction.load import load_data

/Users/coopa33/Projects/vu/dmt-2/.venv/lib/python3.12/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

In [4]:
cwd = os.getcwd()
print(f'current working directory: {cwd}')
pd.set_option("display.max_columns", None)

current working directory: /Users/coopa33/Projects/vu/dmt-2/src/notebooks

In [5]:
sub_sample, train_set, test_set = load_data()

In [18]:
n_rows = 20
display(train_set.head(n_rows))
display(test_set.head(n_rows))
print('train_set shape:', train_set.shape)
print('test_set shape:', test_set.shape)

,srch_id,date_time,site_id,visitor_location_country_id,visitor_hist_starrating,visitor_hist_adr_usd,prop_country_id,prop_id,prop_starrating,prop_review_score,prop_brand_bool,prop_location_score1,prop_location_score2,prop_log_historical_price,price_usd,promotion_flag,srch_destination_id,srch_length_of_stay,srch_booking_window,srch_adults_count,srch_children_count,srch_room_count,srch_saturday_night_bool,srch_query_affinity_score,orig_destination_distance,random_bool,comp1_rate,comp1_inv,comp1_rate_percent_diff,comp2_rate,comp2_inv,comp2_rate_percent_diff,comp3_rate,comp3_inv,comp3_rate_percent_diff,comp4_rate,comp4_inv,comp4_rate_percent_diff,comp5_rate,comp5_inv,comp5_rate_percent_diff,comp6_rate,comp6_inv,comp6_rate_percent_diff,comp7_rate,comp7_inv,comp7_rate_percent_diff,comp8_rate,comp8_inv,comp8_rate_percent_diff
0,1,2013-04-04 08:32:15,12,187,NaN,NaN,219,893,3,3.5,1,2.83,0.0438,4.95,104.77,0,23246,1,0,4,0,1,1,NaN,NaN,1,NaN,NaN,NaN,0.0,0.0,NaN,0.0,0.0,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,NaN
1,1,2013-04-04 08:32:15,12,187,NaN,NaN,219,10404,4,4.0,1,2.20,0.0149,5.03,170.74,0,23246,1,0,4,0,1,1,NaN,NaN,1,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN,0.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,NaN
2,1,2013-04-04 08:32:15,12,187,NaN,NaN,219,21315,3,4.5,1,2.20,0.0245,4.92,179.80,0,23246,1,0,4,0,1,1,NaN,NaN,1,NaN,NaN,NaN,0.0,0.0,NaN,0.0,0.0,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,NaN
3,1,2013-04-04 08:32:15,12,187,NaN,NaN,219,27348,2,4.0,1,2.83,0.0125,4.39,602.77,0,23246,1,0,4,0,1,1,NaN,NaN,1,NaN,NaN,NaN,-1.0,0.0,5.0,-1.0,0.0,5.0,NaN,NaN,NaN,0.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-1.0,0.0,5.0
4,1,2013-04-04 08:32:15,12,187,NaN,NaN,219,29604,4,3.5,1,2.64,0.1241,4.93,143.58,0,23246,1,0,4,0,1,1,NaN,NaN,1,NaN,NaN,NaN,0.0,0.0,NaN,0.0,0.0,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,NaN
5,1,2013-04-04 08:32:15,12,187,NaN,NaN,219,30184,4,4.5,1,2.77,0.1302,5.20,195.32,0,23246,1,0,4,0,1,1,NaN,NaN,1,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,7.0,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,7.0
6,1,2013-04-04 08:32:15,12,187,NaN,NaN,219,44147,3,3.5,1,2.20,0.0356,4.81,129.35,0,23246,1,0,4,0,1,1,NaN,NaN,1,NaN,NaN,NaN,0.0,0.0,NaN,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,NaN
7,1,2013-04-04 08:32:15,12,187,NaN,NaN,219,50984,2,0.0,0,1.61,NaN,4.14,85.37,0,23246,1,0,4,0,1,1,NaN,NaN,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,1,2013-04-04 08:32:15,12,187,NaN,NaN,219,53341,4,4.0,1,2.56,0.1238,5.18,150.05,0,23246,1,0,4,0,1,1,NaN,NaN,1,NaN,NaN,NaN,0.0,0.0,NaN,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,6.0
9,1,2013-04-04 08:32:15,12,187,NaN,NaN,219,56880,4,4.0,1,2.83,0.1028,5.15,280.69,0,23246,1,0,4,0,1,1,NaN,NaN,1,NaN,NaN,NaN,0.0,0.0,NaN,0.0,0.0,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,NaN
10,1,2013-04-04 08:32:15,12,187,NaN,NaN,219,59267,3,0.0,1,2.20,NaN,5.08,190.14,0,23246,1,0,4,0,1,1,NaN,NaN,1,NaN,NaN,NaN,1.0,0.0,11.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,NaN
11,1,2013-04-04 08:32:15,12,187,NaN,NaN,219,59526,3,3.5,0,2.20,0.0377,4.78,100.89,0,23246,1,0,4,0,1,1,NaN,NaN,1,NaN,NaN,NaN,0.0,0.0,NaN,-1.0,0.0,5.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,0.0,31.0
12,1,2013-04-04 08:32:15,12,187,NaN,NaN,219,68914,2,3.0,1,2.20,0.0206,4.44,100.89,0,23246,1,0,4,0,1,1,NaN,NaN,1,NaN,NaN,NaN,0.0,0.0,11.0,0.0,0.0,NaN,NaN,NaN,NaN,0.0,-1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,11.0
13,1,2013-04-04 08:32:15,12,187,NaN,NaN,219,74474,3,4.5,1,2.40,0.1255,5.03,210.84,0,23246,1,0,4,0,1,1,NaN,NaN,1,NaN,NaN,NaN,0.0,0.0,NaN,0.0,0.0,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,NaN
14,1,2013-04-04 08:32:15,12,187,NaN,NaN,219,81437,3,4.0,1,2.30,0.0155,5.03,138.40,0,23246,1,0,4,0,1,1,NaN,NaN,1,NaN,NaN,NaN,0.0,0.0,NaN,0.0,0.0,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,NaN
15,1,2013-04-04 08:32:15,12,187,NaN,NaN,219,85728,2,3.0,1,1.79,0.0072,4.50,100.89,0,23246,1,0,4,0,1,1,NaN,NaN,1,NaN,NaN,NaN,0.0,0.0,NaN,0.0,0.0,8.0,NaN,NaN,NaN,1.0,-1.0,14.0,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,NaN
16,1,2013-04-04 08:32:15,12,187,NaN,NaN,219,88096,4,4.0,1,2.94,0.0660,5.18,152.63,1,23246,1,0,4,0,1,1,NaN,NaN,1,NaN,NaN,NaN,0.0,0.0,5.0,0.0,0.0,5.0,NaN,NaN,NaN,1.0,0.0,5.0,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,15.0
17,1,2013-04-04 08:32:15,12,187,NaN,NaN,219,88127,3,3.0,1,1.39,0.0038,4.80,138.40,0,23246,1,0,4,0,1,1,NaN,NaN,1,NaN,NaN,NaN,0.0,0.0,NaN,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,NaN
18,1,2013-04-04 08:32:15,12,187,NaN,NaN,219,88218,4,3.5,1,2.77,0.1266,4.98,115.12,0,23246,1,0,4,0,1,1,NaN,NaN,1,NaN,NaN,NaN,0.0,0.0,NaN,0.0,0.0,NaN,NaN,NaN,NaN,0.0,-1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,NaN
19,1,2013-04-04 08:32:15,12,187,NaN,NaN,219,89073,4,4.0,1,2.08,0.0150,5.28,191.44,0,23246,1,0,4,0,1,1,NaN,NaN,1,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,5.0,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,5.0

,srch_id,date_time,site_id,visitor_location_country_id,visitor_hist_starrating,visitor_hist_adr_usd,prop_country_id,prop_id,prop_starrating,prop_review_score,prop_brand_bool,prop_location_score1,prop_location_score2,prop_log_historical_price,price_usd,promotion_flag,srch_destination_id,srch_length_of_stay,srch_booking_window,srch_adults_count,srch_children_count,srch_room_count,srch_saturday_night_bool,srch_query_affinity_score,orig_destination_distance,random_bool,comp1_rate,comp1_inv,comp1_rate_percent_diff,comp2_rate,comp2_inv,comp2_rate_percent_diff,comp3_rate,comp3_inv,comp3_rate_percent_diff,comp4_rate,comp4_inv,comp4_rate_percent_diff,comp5_rate,comp5_inv,comp5_rate_percent_diff,comp6_rate,comp6_inv,comp6_rate_percent_diff,comp7_rate,comp7_inv,comp7_rate_percent_diff,comp8_rate,comp8_inv,comp8_rate_percent_diff
0,1,2013-02-02 15:27:40,24,216,NaN,NaN,219,3180,3,4.5,1,2.94,0.0691,5.03,119.00,0,19222,1,10,2,0,1,0,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1,2013-02-02 15:27:40,24,216,NaN,NaN,219,5543,3,4.5,1,2.64,0.0843,4.93,118.00,0,19222,1,10,2,0,1,0,NaN,NaN,0,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,1,2013-02-02 15:27:40,24,216,NaN,NaN,219,14142,2,3.5,1,2.71,0.0556,4.16,49.00,0,19222,1,10,2,0,1,0,NaN,NaN,0,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,0.0,10.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,1,2013-02-02 15:27:40,24,216,NaN,NaN,219,22393,3,4.5,1,2.40,0.0561,5.03,143.00,0,19222,1,10,2,0,1,0,NaN,NaN,0,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,1,2013-02-02 15:27:40,24,216,NaN,NaN,219,24194,3,4.5,1,2.94,0.2090,4.72,79.00,0,19222,1,10,2,0,1,0,NaN,NaN,0,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,1,2013-02-02 15:27:40,24,216,NaN,NaN,219,28181,3,4.5,1,2.30,0.1826,4.68,84.15,0,19222,1,10,2,0,1,0,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,1,2013-02-02 15:27:40,24,216,NaN,NaN,219,34263,3,4.5,1,3.09,0.1300,4.63,79.00,0,19222,1,10,2,0,1,0,NaN,NaN,0,NaN,NaN,NaN,0.0,0.0,6.0,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,6.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,1,2013-02-02 15:27:40,24,216,NaN,NaN,219,37567,2,4.5,0,2.83,0.0138,4.21,52.40,1,19222,1,10,2,0,1,0,NaN,NaN,0,NaN,NaN,NaN,1.0,0.0,11.0,NaN,NaN,NaN,NaN,NaN,NaN,1.0,0.0,27.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,1,2013-02-02 15:27:40,24,216,NaN,NaN,219,50162,2,3.5,1,2.20,0.0808,4.36,49.99,1,19222,1,10,2,0,1,0,NaN,NaN,0,NaN,NaN,NaN,-1.0,0.0,10.0,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,1,2013-02-02 15:27:40,24,216,NaN,NaN,219,54937,3,4.0,1,2.08,0.1649,4.75,83.30,1,19222,1,10,2,0,1,0,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,1,2013-02-02 15:27:40,24,216,NaN,NaN,219,56050,3,4.0,1,2.77,0.1210,4.59,145.00,0,19222,1,10,2,0,1,0,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,1,2013-02-02 15:27:40,24,216,NaN,NaN,219,61632,0,0.0,0,3.04,0.0136,4.62,45.00,0,19222,1,10,2,0,1,0,NaN,NaN,0,NaN,NaN,NaN,1.0,0.0,13.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,1,2013-02-02 15:27:40,24,216,NaN,NaN,219,61934,3,4.5,1,2.89,0.2425,4.69,88.88,1,19222,1,10,2,0,1,0,NaN,NaN,0,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,1,2013-02-02 15:27:40,24,216,NaN,NaN,219,63894,3,4.5,1,2.77,0.2261,4.88,103.98,0,19222,1,10,2,0,1,0,NaN,NaN,0,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,1,2013-02-02 15:27:40,24,216,NaN,NaN,219,72090,3,4.0,1,2.89,0.0466,4.95,79.00,0,19222,1,10,2,0,1,0,NaN,NaN,0,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15,1,2013-02-02 15:27:40,24,216,NaN,NaN,219,73666,3,4.5,1,2.89,0.2272,4.79,149.00,0,19222,1,10,2,0,1,0,NaN,NaN,0,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16,1,2013-02-02 15:27:40,24,216,NaN,NaN,219,74045,3,4.0,1,2.77,0.2003,4.56,89.99,0,19222,1,10,2,0,1,0,NaN,NaN,0,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17,1,2013-02-02 15:27:40,24,216,NaN,NaN,219,78599,4,4.5,1,2.30,0.0895,5.06,158.87,0,19222,1,10,2,0,1,0,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18,1,2013-02-02 15:27:40,24,216,NaN,NaN,219,82231,3,4.5,1,2.77,0.2090,4.92,104.00,0,19222,1,10,2,0,1,0,NaN,NaN,0,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19,1,2013-02-02 15:27:40,24,216,NaN,NaN,219,89466,2,3.0,0,2.08,0.0778,4.31,58.57,0,19222,1,10,2,0,1,0,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

train_set shape: (4958347, 50)
test_set shape: (4959183, 50)

In [14]:
display(train_set.columns)
train_excl_attr = set(train_set.columns) - set(test_set.columns)
display("training exclusive attributes: ", train_excl_attr)

Index(['srch_id', 'date_time', 'site_id', 'visitor_location_country_id',
       'visitor_hist_starrating', 'visitor_hist_adr_usd', 'prop_country_id',
       'prop_id', 'prop_starrating', 'prop_review_score', 'prop_brand_bool',
       'prop_location_score1', 'prop_location_score2',
       'prop_log_historical_price', 'position', 'price_usd', 'promotion_flag',
       'srch_destination_id', 'srch_length_of_stay', 'srch_booking_window',
       'srch_adults_count', 'srch_children_count', 'srch_room_count',
       'srch_saturday_night_bool', 'srch_query_affinity_score',
       'orig_destination_distance', 'random_bool', 'comp1_rate', 'comp1_inv',
       'comp1_rate_percent_diff', 'comp2_rate', 'comp2_inv',
       'comp2_rate_percent_diff', 'comp3_rate', 'comp3_inv',
       'comp3_rate_percent_diff', 'comp4_rate', 'comp4_inv',
       'comp4_rate_percent_diff', 'comp5_rate', 'comp5_inv',
       'comp5_rate_percent_diff', 'comp6_rate', 'comp6_inv',
       'comp6_rate_percent_diff', 'comp7_rate', 'comp7_inv',
       'comp7_rate_percent_diff', 'comp8_rate', 'comp8_inv',
       'comp8_rate_percent_diff', 'click_bool', 'gross_bookings_usd',
       'booking_bool'],
      dtype='str')

'training exclusive attributes: '

{'booking_bool', 'click_bool', 'gross_bookings_usd', 'position'}


- Both the training and test sets have close to 5 million instances.
- Training set has 54 attributes, test set has 50
- The training exclusive attributes are:
    - Booking_bool, click_bool, gross_bookings_usd, position
    - These will be excluded, as they do not exist in the test set

In [15]:
train_set = train_set.drop(columns = train_excl_attr)

## Sparsity

In [16]:
sparsity = sum((train_set == 0).astype(int).sum())/train_set.size
print('sparsity of train_set:', sparsity)
diagnose_data(train_set, name = 'train_set')

sparsity of train_set: 0.13014839017922708
+++ Data Diagnostics +++
Diagnostics for train_set:
pandas DataFrame
Shape: (4958347, 50)
Number of Missing Values: 114913323
Percentage of Missing Values: 46.35%
++++++++++++++++++++++++

- The training set is not particularly sparse
- However, close to half of the data has missing values, which is a problem.
- It's likely that this is systematic missingness: Looking at the first 5 entries of both sets, missingness seems to be pervasive within specific variables:
    - "visitor_hist_starrating", "visitor_hist_adr_usd" : Nulls mean that there is no user history for purchases -> Many customers are new customers. Imputation here could be a neutral value, for example neutral rating and mean average purchase history.
    - "srch_query_affinity_score" : Null means that hotel did not register in searches -> Many hotels did not register in search queries.
    - "orig_destination_distance" : Null means that distance could not be calculated. -> This is potentially a useful attribute, some imputation heuristic could be useful here. For example, we could use "visitor_location_country_id" and compute the distance to the property. 
    - "comp* attributes" : Null means there is no competetive data -> There is no competetive data of certain competitors for certain hotels listed. Question here is what it means that there is no data? Either data is missing at random (measurement error) or competitor x does not have the property in their catalogue, hence no competetive data. The definition of "availability" in the attribute description is not clear: Does no availability mean they have the property, but there are no rooms available, or they do not have the property?

## Expedia 
The following sections tries to investigate and familiarize with the expedia webpage and the associated variables.

*Search-specific attributes*:
These are attributes associated with a specific search of a user at a given time. One search usually includes many hotels, each with individual attributes. 
- srch_id, date_time, site_id, visitor_location_country_id: Search metadata 

*User-specific attributes*
- visitor_hist_starrating, visitor_hist_adr_usd: Historical data of the user, such as average rating and prices of hotels stayed at

*Hotel-specific attributes*
- prop_*